### ISSUE TITLE
Query lang problems

### ISSUE THREAD

**Issue by gtfierro** [gtfierro/giles#32]
```
INFO Mar 06 11:28:21 archiver.go:196 ▶ delete Actuator/override where has Actuator/override;
2015/03/06 11:28:21 http: panic serving [::1]:36149: runtime error: index out of range
goroutine 13175839 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/gtfierro/giles/archiver.getnodeAt(0x3, 0xc2081d63c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/ast.go:267 +0x474
github.com/gtfierro/giles/archiver.parseWhere(0xc2081d63c0, 0xc208606310)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/ast.go:244 +0x6a7
github.com/gtfierro/giles/archiver.makeAST(0xc208606300, 0x5, 0x8, 0x5, 0x0, 0x0)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/ast.go:311 +0x2ad
github.com/gtfierro/giles/archiver.parse(0xc208810980, 0x35, 0x35)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/ast.go:318 +0x63
github.com/gtfierro/giles/archiver.(*Archiver).HandleQuery(0xc208039040, 0xc208810980, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/archiver.go:198 +0x1f4
github.com/gtfierro/giles/httphandler.QueryHandler(0xc208039040, 0x7f2ede32f190, 0xc20810d220, 0xc2089c4d00, 0x0, 0x0, 0x0)
        /home/gabe/go/src/github.com/gtfierro/giles/httphandler/handlers.go:129 +0x356
github.com/gtfierro/giles/httphandler.func·001(0x7f2ede32f190, 0xc20810d220, 0xc2089c4d00, 0x0, 0x0, 0x0)
        /home/gabe/go/src/github.com/gtfierro/giles/httphandler/handlers.go:56 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc20817c000, 0x7f2ede32f190, 0xc20810d220, 0xc2089c4d00)
        /home/gabe/go/src/github.com/julienschmidt/httprouter/router.go:281 +0x188
net/http.(*ServeMux).ServeHTTP(0xc20803aae0, 0x7f2ede32f190, 0xc20810d220, 0xc2089c4d00)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc2080e6300, 0x7f2ede32f190, 0xc20810d220, 0xc2089c4d00)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20810d180)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by gtfierro** [comment]
Should be able to fix these problems in the query lang rewrite at https://github.com/gtfierro/giles/tree/master/yacc
