### ISSUE TITLE
Bug probably arises during race condition in republish

### ISSUE THREAD

**Issue by gtfierro** [gtfierro/giles#36]
https://github.com/gtfierro/giles/blob/master/archiver/republish.go#L267-L276

```
2015/04/06 16:31:54 http: panic serving 169.229.223.190:56165: runtime error: slice bounds out of range
goroutine 2093938 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/gtfierro/giles/archiver.(*Republisher).EvaluateQuery(0xc20802c240, 0xc2081344e0, 0x23)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/republish.go:271 +0x1749
github.com/gtfierro/giles/archiver.(*Republisher).MetadataChange(0xc20802c240, 0xc208188e70)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/republish.go:214 +0x1d3
github.com/gtfierro/giles/archiver.(*Archiver).AddData(0xc2080363c0, 0xc208392630, 0xc20810b92a, 0x8, 0x0, 0x0)
        /home/gabe/go/src/github.com/gtfierro/giles/archiver/archiver.go:192 +0x6a0
github.com/gtfierro/giles/httphandler.AddReadingHandler(0xc2080363c0, 0x7fc16e3e1ad8, 0xc20805dae0, 0xc20812fd40, 0xc20810b980, 0x1, 0x1)
        /home/gabe/go/src/github.com/gtfierro/giles/httphandler/handlers.go:97 +0x2ce
github.com/gtfierro/giles/httphandler.func·001(0x7fc16e3e1ad8, 0xc20805dae0, 0xc20812fd40, 0xc20810b980, 0x1, 0x1)
        /home/gabe/go/src/github.com/gtfierro/giles/httphandler/handlers.go:56 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc20801e740, 0x7fc16e3e1ad8, 0xc20805dae0, 0xc20812fd40)
        /home/gabe/go/src/github.com/julienschmidt/httprouter/router.go:281 +0x188
net/http.(*ServeMux).ServeHTTP(0xc208038750, 0x7fc16e3e1ad8, 0xc20805dae0, 0xc20812fd40)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20802c660, 0x7fc16e3e1ad8, 0xc20805dae0, 0xc20812fd40)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20805da40)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by gtfierro** [comment]
Haven't run into this since some recent commits, so most likely fixed by ed8708a4e8727292f76e8f7ff2854a2cfe3061e0, 618bddaae1566328deb408b55348ccd198bee964, 76dd9a10d76fc53ee33c1fa02869c2f1e5b80e18
